version: '3.8'
name: inception

x-services-common-configs: &common-configs
  init: true
  restart: always
  env_file: ./.env
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "2048m"

services:
  nginx:
    hostname: nginx
    <<: *common-configs
    build: ./requirements/nginx
    depends_on: 
      - wordpress
    volumes: 
      - $DATA/www-data:/var/www/html
    networks:
      - front-tier
    ports:
      - 443:443
  wordpress:
    hostname: wordpress
    <<: *common-configs
    build: ./requirements/wordpress
    depends_on: 
      - mariadb
    volumes:
      - $DATA/www-data:/var/www/html
    networks:
      - front-tier
      - back-tier
  mariadb:
    hostname: mariadb
    <<: *common-configs
    build: ./requirements/mariadb
    volumes:
      - $DATA/db-data:/var/lib/mysql
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
